// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(BankaContext))]
    partial class BankaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebTemplate.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RacunId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RacunId")
                        .IsUnique();

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("WebTemplate.Models.Racun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BrojRacuna")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Sredstva")
                        .HasColumnType("numeric");

                    b.Property<string>("Valuta")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Racuni");
                });

            modelBuilder.Entity("WebTemplate.Models.Stednja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cilj")
                        .HasColumnType("numeric");

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("integer");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Vrednost")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Stednje");
                });

            modelBuilder.Entity("WebTemplate.Models.Transakcija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("numeric");

                    b.Property<int>("RacunId")
                        .HasColumnType("integer");

                    b.Property<string>("Svrha")
                        .HasColumnType("text");

                    b.Property<string>("TekuciReceiver")
                        .HasColumnType("text");

                    b.Property<string>("TekuciSender")
                        .HasColumnType("text");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RacunId");

                    b.ToTable("Transakcije");
                });

            modelBuilder.Entity("WebTemplate.Models.Korisnik", b =>
                {
                    b.HasOne("WebTemplate.Models.Racun", "Racun")
                        .WithOne("Korisnik")
                        .HasForeignKey("WebTemplate.Models.Korisnik", "RacunId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Racun");
                });

            modelBuilder.Entity("WebTemplate.Models.Stednja", b =>
                {
                    b.HasOne("WebTemplate.Models.Korisnik", "Korisnik")
                        .WithMany("Stednje")
                        .HasForeignKey("KorisnikId");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("WebTemplate.Models.Transakcija", b =>
                {
                    b.HasOne("WebTemplate.Models.Racun", "Racun")
                        .WithMany("Transakcije")
                        .HasForeignKey("RacunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Racun");
                });

            modelBuilder.Entity("WebTemplate.Models.Korisnik", b =>
                {
                    b.Navigation("Stednje");
                });

            modelBuilder.Entity("WebTemplate.Models.Racun", b =>
                {
                    b.Navigation("Korisnik");

                    b.Navigation("Transakcije");
                });
#pragma warning restore 612, 618
        }
    }
}
